# Book settings
title:
author: Development Data Group
logo: docs/images/logo.png
only_build_toc_files: true

repository:
  url: https://github.com/worldbank/template
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://worldbank.github.io/template
  extra_footer: |
    <div>
      For illustrative purposes and does not imply the expression of any opinion on the part of the World Bank, concerning the legal status of any country or territory or concerning the delimitation of frontiers or boundaries.
    </div>
    <br>
    <div>
        <b>All content (unless otherwise specified) is subject to the <a href="https://www.mozilla.org/en-US/MPL/">Mozilla Public License</a>.</b>
    </div>
  favicon: docs/images/favicon.ico

#######################################################################################
# Execution settings
execute:
  execute_notebooks: "off"

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
  - docs/bibliography.bib

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
